### ISSUE TITLE
can't create a new ressource 

### ISSUE THREAD

**Issue by vahuck** [reflow-project/zenpub-client#42]
hi there, I've successfully created a new collection, but when I tried to create a 'new ressource', the "publish" button doesn't seem to work as nothing happens and the info has not been saved. 

Thx

**Comment by viktorsmari** [comment]
Thanks for reporting @vahuck !

Can you take a screenshot or send us the URL of the page you are working on?


It might be that you are trying to create a 'resource' that we inherited from the original project (MoodleNet) that this ReflowOS is built on top of.

We plan on removing these Collections and their `resources` from the app #32 so it won't confuse our users.

Right now we can create **Intents** from the top navbar:
![2021-04-23_12-28-30](https://user-images.githubusercontent.com/1689020/115858692-911dce80-a42f-11eb-8756-113b419d5d40.png)

And there you can select which Community it belongs to from a dropdown.
![2021-04-23_12-30-17](https://user-images.githubusercontent.com/1689020/115858798-b0b4f700-a42f-11eb-9406-9e1f570223c6.png)

The intent will then be visible at the bottom (after refreshing the page)
![2021-04-23_12-30-46](https://user-images.githubusercontent.com/1689020/115858905-cd512f00-a42f-11eb-8174-21511cbfc824.png)

**Comment by vahuck** [comment]
Hi Viktor, thx for the fast reply I just noticed your answer sorry for the delay ;  it is indeed as you suspected
I have successfully created a ressource through "create an new intent"
